pub mod poseidon_params;
pub mod poseidon_params_width_9;
pub mod poseidon_params_width_32;
pub mod poseidon_params_width_3;
pub mod poseidon_params_width_4;
// pub mod poseidon_params_width_61;
pub mod spec;
pub mod spec_width_9;
pub mod spec_width_32;
pub mod spec_width_3;
pub mod spec_width_4;
// pub mod spec_width_61;
